#Part 1 to Part 7

#7)#

#Total cost =  2192870.0#

#Number of truckload of EV's are ::#

Between ahmedabad  and  Jodhpur : 300.0

Between ahmedabad  and  Dibrugarh : 45.0

Between ahmedabad  and  Raipur : 5.0

Between Bengaluru  and  Trichy : 120.0

between  Bengaluru  and  Vijaywarah : 65.0

between  Chennai  and  Trichy : 305.0

between  Delhi  and  Shimla : 95.0

between  Delhi  and  Dibrugarh : 85.0

between  Kolkata  and  Dibrugarh : 95.0

between  Kolkata  and  Agartala : 110.0

between  Lucknow  and  Shimla : 175.0

between  Mumbai  and  Hassan : 205.0

between  Mumbai  and  Raipur : 120.0

between  Hydrabad  and  Vijaywarah : 310.0

between  Hydrabad  and  Raipur : 60.0

In [6]:
!pip install -q pyomo

In [7]:
from pyomo.environ import * 

In [8]:
import numpy as np

In [9]:
import pandas as pd

For more on pandas library please check https://pandas.pydata.org/pandas-docs/version/0.15/tutorials.html

In [10]:
data_csvfile = pd.read_csv('lab6_ex1.csv')

In [11]:
data_csvfile.index

RangeIndex(start=0, stop=9, step=1)

In [12]:
print('num rows:', len(data_csvfile.index))

num rows: 9


In [13]:
#to get the row contents corresponding to Ahmedabad
print(data_csvfile.iloc[0,:])

Warehouses         ahmedabad
Hassan                   827
Jodhpur                  817
Trichy                  1470
Shimla                  2272
Vijaywarah              1615
Dibrugarh               3143
Raipur                  1264
Agartala                4465
Available stock          350
Name: 0, dtype: object


In [14]:
#to get the row contents corresponding to Bengaluru
print(data_csvfile.iloc[1,:])

Warehouses         Bengaluru
Hassan                   559
Jodhpur                 1832
Trichy                   751
Shimla                  3772
Vijaywarah               637
Dibrugarh               3773
Raipur                  1856
Agartala                5459
Available stock          185
Name: 1, dtype: object


In [15]:
data_csvfile.columns

Index(['Warehouses', 'Hassan', 'Jodhpur', 'Trichy', 'Shimla', 'Vijaywarah',
       'Dibrugarh', 'Raipur', 'Agartala', 'Available stock'],
      dtype='object')

In [16]:
print('num  columns: ',len(data_csvfile.columns))

num  columns:  10


In [17]:
#to get the column contents corresponding to Hassan
print(data_csvfile.iloc[:,1])

0     827
1     559
2    1109
3    2943
4    3742
5    2353
6    1356
7     195
8     205
Name: Hassan, dtype: int64


In [18]:
#to get the column contents corresponding to Jodhpur
print(data_csvfile.iloc[:,2])

0     817
1    1832
2    2443
3    1471
4    3089
5    1160
6    1617
7    1862
8     300
Name: Jodhpur, dtype: int64


In [19]:
# create a model
model_lab5_ex1 = ConcreteModel()

In [20]:
# we can set certain values using python variables
M = len(data_csvfile.index)-1 #we declare a Python variable M denoting the number of Washing Machine Units  
print('num washing machine units: ',M)

num washing machine units:  8


In [21]:
N = len(data_csvfile.columns)-2 #we declare a Python variable N denoting the number of Markets
print('num markets: ',N)

num markets:  8


In [22]:
row_indices = range(M)
col_indices = range(N)

print(row_indices)
print(col_indices)

range(0, 8)
range(0, 8)


In [23]:
#to get the contents of costs alone from the file we use the following
for row_idx in row_indices:
  for col_idx in col_indices:
    print('cost[',row_idx,'][',col_idx+1,']:',data_csvfile.iloc[row_idx, col_idx+1])

cost[ 0 ][ 1 ]: 827
cost[ 0 ][ 2 ]: 817
cost[ 0 ][ 3 ]: 1470
cost[ 0 ][ 4 ]: 2272
cost[ 0 ][ 5 ]: 1615
cost[ 0 ][ 6 ]: 3143
cost[ 0 ][ 7 ]: 1264
cost[ 0 ][ 8 ]: 4465
cost[ 1 ][ 1 ]: 559
cost[ 1 ][ 2 ]: 1832
cost[ 1 ][ 3 ]: 751
cost[ 1 ][ 4 ]: 3772
cost[ 1 ][ 5 ]: 637
cost[ 1 ][ 6 ]: 3773
cost[ 1 ][ 7 ]: 1856
cost[ 1 ][ 8 ]: 5459
cost[ 2 ][ 1 ]: 1109
cost[ 2 ][ 2 ]: 2443
cost[ 2 ][ 3 ]: 577
cost[ 2 ][ 4 ]: 3865
cost[ 2 ][ 5 ]: 798
cost[ 2 ][ 6 ]: 3521
cost[ 2 ][ 7 ]: 1984
cost[ 2 ][ 8 ]: 5303
cost[ 3 ][ 1 ]: 2943
cost[ 3 ][ 2 ]: 1471
cost[ 3 ][ 3 ]: 4676
cost[ 3 ][ 4 ]: 1337
cost[ 3 ][ 5 ]: 2702
cost[ 3 ][ 6 ]: 2741
cost[ 3 ][ 7 ]: 2482
cost[ 3 ][ 8 ]: 4148
cost[ 4 ][ 1 ]: 3742
cost[ 4 ][ 2 ]: 3089
cost[ 4 ][ 3 ]: 2931
cost[ 4 ][ 4 ]: 3199
cost[ 4 ][ 5 ]: 2226
cost[ 4 ][ 6 ]: 1739
cost[ 4 ][ 7 ]: 1691
cost[ 4 ][ 8 ]: 2128
cost[ 5 ][ 1 ]: 2353
cost[ 5 ][ 2 ]: 1160
cost[ 5 ][ 3 ]: 3295
cost[ 5 ][ 4 ]: 368
cost[ 5 ][ 5 ]: 2369
cost[ 5 ][ 6 ]: 2365
cost[ 5 ][ 7 ]: 1293
cost[ 5 ][ 8 ]: 3642


In [24]:
#declare the decision variables in the model
model_lab5_ex1.x = Var(row_indices, col_indices, domain= NonNegativeIntegers)

In [25]:
model_lab5_ex1.objective = Objective(expr=sum(data_csvfile.iloc[i,j+1]*model_lab5_ex1.x[i,j] for i in row_indices for j in col_indices),sense=minimize)

In [26]:
model_lab5_ex1.constraints = ConstraintList()

In [27]:
#to get the supply (or production) limit at washing machine units from the file we can use the following
print(data_csvfile.iloc[:8,N+1])

0    350
1    185
2    305
3    180
4    205
5    175
6    325
7    370
Name: Available stock, dtype: int64


In [28]:
#to get the demands at markets from the file we can use the following
print(data_csvfile.iloc[M,1:N+1])

Hassan        205
Jodhpur       300
Trichy        425
Shimla        270
Vijaywarah    375
Dibrugarh     225
Raipur        185
Agartala      110
Name: 8, dtype: object


In [29]:
#first We will add the supply (or production) limit constraints
#supply constraint for Ahmedabad
model_lab5_ex1.constraints.add(expr=sum(model_lab5_ex1.x[0,j] for j in col_indices) <= data_csvfile.iloc[0,N+1]) 

#supply constraint for Bengaluru
model_lab5_ex1.constraints.add(expr=sum(model_lab5_ex1.x[1,j] for j in col_indices) <= data_csvfile.iloc[1,N+1]) 

#supply constraint for chennai
model_lab5_ex1.constraints.add(expr=sum(model_lab5_ex1.x[2,j] for j in col_indices) <= data_csvfile.iloc[2,N+1]) 

#supply constraint for Delhi
model_lab5_ex1.constraints.add(expr=sum(model_lab5_ex1.x[3,j] for j in col_indices) <= data_csvfile.iloc[3,N+1]) 

#supply constraint for Kokata
model_lab5_ex1.constraints.add(expr=sum(model_lab5_ex1.x[4,j] for j in col_indices) <= data_csvfile.iloc[4,N+1]) 

#supply constraint for Lucknow
model_lab5_ex1.constraints.add(expr=sum(model_lab5_ex1.x[5,j] for j in col_indices) <= data_csvfile.iloc[5,N+1]) 

#supply constraint for Mumbai
model_lab5_ex1.constraints.add(expr=sum(model_lab5_ex1.x[6,j] for j in col_indices) <= data_csvfile.iloc[6,N+1]) 

#supply constraint for Hydrabad
model_lab5_ex1.constraints.add(expr=sum(model_lab5_ex1.x[7,j] for j in col_indices) <= data_csvfile.iloc[7,N+1]) 


In [30]:
#Now we will add the demand constraints
#demand constraint for Hassan
model_lab5_ex1.constraints.add(expr=sum(model_lab5_ex1.x[i,0] for i in row_indices) == data_csvfile.iloc[M,1])

#demand constraint for Jodhpur
model_lab5_ex1.constraints.add(expr=sum(model_lab5_ex1.x[i,1] for i in row_indices) == data_csvfile.iloc[M,2])

#demand constraint for Trichy
model_lab5_ex1.constraints.add(expr=sum(model_lab5_ex1.x[i,2] for i in row_indices) == data_csvfile.iloc[M,3])

#demand constraint for Shimla
model_lab5_ex1.constraints.add(expr=sum(model_lab5_ex1.x[i,3] for i in row_indices) == data_csvfile.iloc[M,4])

#demand constraint for Vijaywada
model_lab5_ex1.constraints.add(expr=sum(model_lab5_ex1.x[i,4] for i in row_indices) == data_csvfile.iloc[M,5])

#demand constraint for Dibrugarh
model_lab5_ex1.constraints.add(expr=sum(model_lab5_ex1.x[i,5] for i in row_indices) == data_csvfile.iloc[M,6])

#demand constraint for Raipur
model_lab5_ex1.constraints.add(expr=sum(model_lab5_ex1.x[i,6] for i in row_indices) == data_csvfile.iloc[M,7])

#demand constraint for Agartala
model_lab5_ex1.constraints.add(expr=sum(model_lab5_ex1.x[i,7] for i in row_indices) == data_csvfile.iloc[M,8])


In [31]:
model_lab5_ex1.pprint()

4 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   16 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}
    x_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain              : Size : Members
        None :     2 : x_index_0*x_index_1 :   64 : {(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7)}
    x_index_0 : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
    

In [32]:
!apt-get install -y -qq coinor-cbc

Selecting previously unselected package coinor-libcoinutils3v5.
(Reading database ... 155569 files and directories currently installed.)
Preparing to unpack .../0-coinor-libcoinutils3v5_2.10.14+repack1-1_amd64.deb ...
Unpacking coinor-libcoinutils3v5 (2.10.14+repack1-1) ...
Selecting previously unselected package coinor-libosi1v5.
Preparing to unpack .../1-coinor-libosi1v5_0.107.9+repack1-1_amd64.deb ...
Unpacking coinor-libosi1v5 (0.107.9+repack1-1) ...
Selecting previously unselected package coinor-libclp1.
Preparing to unpack .../2-coinor-libclp1_1.16.11+repack1-1_amd64.deb ...
Unpacking coinor-libclp1 (1.16.11+repack1-1) ...
Selecting previously unselected package coinor-libcgl1.
Preparing to unpack .../3-coinor-libcgl1_0.59.10+repack1-1_amd64.deb ...
Unpacking coinor-libcgl1 (0.59.10+repack1-1) ...
Selecting previously unselected package coinor-libcbc3.
Preparing to unpack .../4-coinor-libcbc3_2.9.9+repack1-1_amd64.deb ...
Unpacking coinor-libcbc3 (2.9.9+repack1-1) ...
Selecting p

In [33]:
opt_cbc = SolverFactory('cbc')

In [34]:
result = opt_cbc.solve(model_lab5_ex1)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal


In [35]:
# display solution
print('\nObjective = ', model_lab5_ex1.objective())

print('\nDecision Variables')
for i in row_indices:
  for j in col_indices:
    print('Num washing machine between ',data_csvfile['Warehouses'][i],' and ', data_csvfile.columns[j+1],':', model_lab5_ex1.x[i,j].value)

print('\nConstraints')
model_lab5_ex1.constraints.display()


Objective =  2192870.0

Decision Variables
Num washing machine between  ahmedabad  and  Hassan : 0.0
Num washing machine between  ahmedabad  and  Jodhpur : 300.0
Num washing machine between  ahmedabad  and  Trichy : 0.0
Num washing machine between  ahmedabad  and  Shimla : 0.0
Num washing machine between  ahmedabad  and  Vijaywarah : 0.0
Num washing machine between  ahmedabad  and  Dibrugarh : 45.0
Num washing machine between  ahmedabad  and  Raipur : 5.0
Num washing machine between  ahmedabad  and  Agartala : 0.0
Num washing machine between  Bengaluru  and  Hassan : 0.0
Num washing machine between  Bengaluru  and  Jodhpur : 0.0
Num washing machine between  Bengaluru  and  Trichy : 120.0
Num washing machine between  Bengaluru  and  Shimla : 0.0
Num washing machine between  Bengaluru  and  Vijaywarah : 65.0
Num washing machine between  Bengaluru  and  Dibrugarh : 0.0
Num washing machine between  Bengaluru  and  Raipur : 0.0
Num washing machine between  Bengaluru  and  Agartala : 0.0
Nu

#Part 8 to 9#

#8)#

Lucknow-Shimla link is disrupted means there is no link between them so we do not doing transportation between them. As per requirement we have increase the cost of this link so that transportation has not been done here as it is a minimization problem

#9)#
#New Total Cost =  2380570.0#

#Non-zero flows on the network are given below ::#
between  ahmedabad  and  Jodhpur : 300.0

between  ahmedabad  and  Raipur : 50.0

between  Bengaluru  and  Trichy : 120.0

between  Bengaluru  and  Vijaywarah : 65.0

between  Chennai  and  Trichy : 305.0

between  Delhi  and  Shimla : 180.0

between  Kolkata  and  Dibrugarh : 95.0

between  Kolkata  and  Agartala : 110.0

between  Lucknow  and  Dibrugarh : 130.0

between  Lucknow  and  Raipur : 45.0

between  Mumbai  and  Hassan : 205.0

between  Mumbai  and  Shimla : 90.0

between  Mumbai  and  Raipur : 30.0

between  Hydrabad  and  Vijaywarah : 310.0

between  Hydrabad  and  Raipur : 60.0



In [36]:
data_csvfile.iloc[5, 4] = 10000000000

In [37]:
model_lab5_ex1.objective = Objective(expr=sum(data_csvfile.iloc[i,j+1]*model_lab5_ex1.x[i,j] for i in row_indices for j in col_indices),sense=minimize)

This is usually indicative of a modelling error.
To avoid this warning, use block.del_component() and block.add_component().


In [38]:
!apt-get install -y -qq coinor-cbc

In [39]:
opt_cbc = SolverFactory('cbc')

In [40]:
result = opt_cbc.solve(model_lab5_ex1)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal


In [41]:
# display solution
print('\nObjective = ', model_lab5_ex1.objective())

print('\nDecision Variables')
for i in row_indices:
  for j in col_indices:
    print('Num washing machine between ',data_csvfile['Warehouses'][i],' and ', data_csvfile.columns[j+1],':', model_lab5_ex1.x[i,j].value)

print('\nConstraints')
model_lab5_ex1.constraints.display()


Objective =  2380570.0

Decision Variables
Num washing machine between  ahmedabad  and  Hassan : 0.0
Num washing machine between  ahmedabad  and  Jodhpur : 300.0
Num washing machine between  ahmedabad  and  Trichy : 0.0
Num washing machine between  ahmedabad  and  Shimla : 0.0
Num washing machine between  ahmedabad  and  Vijaywarah : 0.0
Num washing machine between  ahmedabad  and  Dibrugarh : 0.0
Num washing machine between  ahmedabad  and  Raipur : 50.0
Num washing machine between  ahmedabad  and  Agartala : 0.0
Num washing machine between  Bengaluru  and  Hassan : 0.0
Num washing machine between  Bengaluru  and  Jodhpur : 0.0
Num washing machine between  Bengaluru  and  Trichy : 120.0
Num washing machine between  Bengaluru  and  Shimla : 0.0
Num washing machine between  Bengaluru  and  Vijaywarah : 65.0
Num washing machine between  Bengaluru  and  Dibrugarh : 0.0
Num washing machine between  Bengaluru  and  Raipur : 0.0
Num washing machine between  Bengaluru  and  Agartala : 0.0
Nu

#Part 10#

In [42]:
data_csvfile.iloc[4, 6] = 10000000000
data_csvfile.iloc[3, 7] = 10000000000

In [43]:
model_lab5_ex1.objective = Objective(expr=sum(data_csvfile.iloc[i,j+1]*model_lab5_ex1.x[i,j] for i in row_indices for j in col_indices),sense=minimize)

This is usually indicative of a modelling error.
To avoid this warning, use block.del_component() and block.add_component().


In [44]:
result = opt_cbc.solve(model_lab5_ex1)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal


In [45]:
# display solution
print('\nObjective = ', model_lab5_ex1.objective())

print('\nDecision Variables')
for i in row_indices:
  for j in col_indices:
    print('Num washing machine between ',data_csvfile['Warehouses'][i],' and ', data_csvfile.columns[j+1],':', model_lab5_ex1.x[i,j].value)

print('\nConstraints')
model_lab5_ex1.constraints.display()


Objective =  2518200.0

Decision Variables
Num washing machine between  ahmedabad  and  Hassan : 0.0
Num washing machine between  ahmedabad  and  Jodhpur : 300.0
Num washing machine between  ahmedabad  and  Trichy : 0.0
Num washing machine between  ahmedabad  and  Shimla : 0.0
Num washing machine between  ahmedabad  and  Vijaywarah : 0.0
Num washing machine between  ahmedabad  and  Dibrugarh : 50.0
Num washing machine between  ahmedabad  and  Raipur : 0.0
Num washing machine between  ahmedabad  and  Agartala : 0.0
Num washing machine between  Bengaluru  and  Hassan : 0.0
Num washing machine between  Bengaluru  and  Jodhpur : 0.0
Num washing machine between  Bengaluru  and  Trichy : 120.0
Num washing machine between  Bengaluru  and  Shimla : 0.0
Num washing machine between  Bengaluru  and  Vijaywarah : 65.0
Num washing machine between  Bengaluru  and  Dibrugarh : 0.0
Num washing machine between  Bengaluru  and  Raipur : 0.0
Num washing machine between  Bengaluru  and  Agartala : 0.0
Nu

#11)#

Total cost =  2518200.0

the number of truck-loads of EVs that are transported from warehouses to markets are given below 

between  ahmedabad  and  Jodhpur : 300.0

between  ahmedabad  and  Dibrugarh : 50.0

between  Bengaluru  and  Trichy : 120.0

between  Bengaluru  and  Vijaywarah : 65.0

between  Chennai  and  Trichy : 305.0

between  Delhi  and  Shimla : 180.0

between  Kolkata  and  Raipur : 95.0

between  Kolkata  and  Agartala : 110.0

between  Lucknow  and  Dibrugarh : 175.0

between  Mumbai  and  Hassan : 205.0

between  Mumbai  and  Shimla : 90.0

between  Mumbai  and  Raipur : 30.0

between  Hydrabad  and  Vijaywarah : 310.0

between  Hydrabad  and  Raipur : 60.0



#Observation of all changes as follows#

1. At first Lucknow  and  Shimla : 175.0 and cost = 2192870.0

2. After disruption the link between these two the number of truckloads distributed as

Lucknow and Dibrugarh : 130.0

Lucknow and Raipur : 45.0

also the cost has been increased. New cost = 2380570.0

3. before disruption of kolkata-dibrugarh, number of truckloads between Kolkata and Dibrugarh : 95.0, which has now transferred to Raipur i.e Kolkata and Raipur : 95.0 after disruption.

4. Before, Lucknow and Dibrugarh : 130.0, Lucknow and Raipur : 45.0

But after disruption between delhi-raipur, now Lucknow and Dibrugarh : 175.0

5. The total cost has also increased to 2518200.0